export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADDROLE = 'ADDROLE';
export const OPENERRORMODAL = 'OPENERRORMODAL';
export const OPENAPPMODAL = 'OPENAPPMODAL';
export const OPENDATASETMODAL = 'OPENDATASETMODAL';
