/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:11fedde8-7986-460d-a91a-d68710205aa1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gxjsNZ82v",
    "aws_user_pools_web_client_id": "5nrhkbejfsq8mgi5jc08586maa",
    "oauth": {
        "domain": "artificien.auth.us-east-1.amazoncognito.com"
    }
};


export default awsmobile;
